language: android
jdk: oraclejdk8
script:
  - ./gradlew build

android:

  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+

  components:
    # https://docs.travis-ci.com/user/languages/android/#Installing-a-newer-SDK-Platform-Tools-revision
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-29.0.2

    # The SDK version used to compile your project
    - android-28
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository